/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPesertaRouteImport } from './routes/_authenticated/peserta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPesertaIndexRouteImport } from './routes/_authenticated/peserta.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiFilesIdRouteImport } from './routes/api.files.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUjianRouteImport } from './routes/_authenticated/admin.ujian'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminPesertaRouteImport } from './routes/_authenticated/admin.peserta'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin.pengaturan'
import { Route as AuthenticatedAdminModulRouteImport } from './routes/_authenticated/admin.modul'
import { Route as AuthenticatedAdminLaporanRouteImport } from './routes/_authenticated/admin.laporan'
import { Route as AuthenticatedAdminHasilRouteImport } from './routes/_authenticated/admin.hasil'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin.files'
import { Route as AuthenticatedAdminEvaluasiRouteImport } from './routes/_authenticated/admin.evaluasi'
import { Route as AuthenticatedAdminLeaderboardIndexRouteImport } from './routes/_authenticated/admin.leaderboard.index'
import { Route as AuthenticatedPesertaUjianIdRouteImport } from './routes/_authenticated/peserta.ujian.$id'
import { Route as AuthenticatedAdminUsersRolesRouteImport } from './routes/_authenticated/admin.users.roles'
import { Route as AuthenticatedAdminUjianIdRouteImport } from './routes/_authenticated/admin.ujian.$id'
import { Route as AuthenticatedAdminPesertaOnlineRouteImport } from './routes/_authenticated/admin.peserta.online'
import { Route as AuthenticatedAdminPesertaKartuRouteImport } from './routes/_authenticated/admin.peserta.kartu'
import { Route as AuthenticatedAdminPesertaGroupRouteImport } from './routes/_authenticated/admin.peserta.group'
import { Route as AuthenticatedAdminModulImportWordRouteImport } from './routes/_authenticated/admin.modul.import-word'
import { Route as AuthenticatedAdminModulImportRouteImport } from './routes/_authenticated/admin.modul.import'
import { Route as AuthenticatedAdminLeaderboardIdRouteImport } from './routes/_authenticated/admin.leaderboard.$id'
import { Route as AuthenticatedAdminLaporanRekapRouteImport } from './routes/_authenticated/admin.laporan.rekap'
import { Route as AuthenticatedAdminLaporanAnalisisRouteImport } from './routes/_authenticated/admin.laporan.analisis'
import { Route as AuthenticatedAdminHasilIdRouteImport } from './routes/_authenticated/admin.hasil.$id'
import { Route as AuthenticatedAdminEvaluasiIdRouteImport } from './routes/_authenticated/admin.evaluasi.$id'
import { Route as AuthenticatedPesertaUjianIdKerjakanRouteImport } from './routes/_authenticated/peserta.ujian.$id.kerjakan'
import { Route as AuthenticatedPesertaUjianIdHasilRouteImport } from './routes/_authenticated/peserta.ujian.$id.hasil'
import { Route as AuthenticatedAdminUjianIdTokenRouteImport } from './routes/_authenticated/admin.ujian.$id.token'
import { Route as AuthenticatedAdminUjianIdPesertaRouteImport } from './routes/_authenticated/admin.ujian.$id.peserta'
import { Route as AuthenticatedAdminTopikIdSoalRouteImport } from './routes/_authenticated/admin.topik.$id.soal'
import { Route as AuthenticatedAdminModulIdTopikRouteImport } from './routes/_authenticated/admin.modul.$id.topik'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPesertaRoute = AuthenticatedPesertaRouteImport.update({
  id: '/peserta',
  path: '/peserta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPesertaIndexRoute =
  AuthenticatedPesertaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUjianRoute = AuthenticatedAdminUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPesertaRoute =
  AuthenticatedAdminPesertaRouteImport.update({
    id: '/peserta',
    path: '/peserta',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulRoute = AuthenticatedAdminModulRouteImport.update({
  id: '/modul',
  path: '/modul',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLaporanRoute =
  AuthenticatedAdminLaporanRouteImport.update({
    id: '/laporan',
    path: '/laporan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHasilRoute = AuthenticatedAdminHasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEvaluasiRoute =
  AuthenticatedAdminEvaluasiRouteImport.update({
    id: '/evaluasi',
    path: '/evaluasi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeaderboardIndexRoute =
  AuthenticatedAdminLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPesertaUjianIdRoute =
  AuthenticatedPesertaUjianIdRouteImport.update({
    id: '/ujian/$id',
    path: '/ujian/$id',
    getParentRoute: () => AuthenticatedPesertaRoute,
  } as any)
const AuthenticatedAdminUsersRolesRoute =
  AuthenticatedAdminUsersRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminUjianIdRoute =
  AuthenticatedAdminUjianIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUjianRoute,
  } as any)
const AuthenticatedAdminPesertaOnlineRoute =
  AuthenticatedAdminPesertaOnlineRouteImport.update({
    id: '/online',
    path: '/online',
    getParentRoute: () => AuthenticatedAdminPesertaRoute,
  } as any)
const AuthenticatedAdminPesertaKartuRoute =
  AuthenticatedAdminPesertaKartuRouteImport.update({
    id: '/kartu',
    path: '/kartu',
    getParentRoute: () => AuthenticatedAdminPesertaRoute,
  } as any)
const AuthenticatedAdminPesertaGroupRoute =
  AuthenticatedAdminPesertaGroupRouteImport.update({
    id: '/group',
    path: '/group',
    getParentRoute: () => AuthenticatedAdminPesertaRoute,
  } as any)
const AuthenticatedAdminModulImportWordRoute =
  AuthenticatedAdminModulImportWordRouteImport.update({
    id: '/import-word',
    path: '/import-word',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)
const AuthenticatedAdminModulImportRoute =
  AuthenticatedAdminModulImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)
const AuthenticatedAdminLeaderboardIdRoute =
  AuthenticatedAdminLeaderboardIdRouteImport.update({
    id: '/leaderboard/$id',
    path: '/leaderboard/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLaporanRekapRoute =
  AuthenticatedAdminLaporanRekapRouteImport.update({
    id: '/rekap',
    path: '/rekap',
    getParentRoute: () => AuthenticatedAdminLaporanRoute,
  } as any)
const AuthenticatedAdminLaporanAnalisisRoute =
  AuthenticatedAdminLaporanAnalisisRouteImport.update({
    id: '/analisis',
    path: '/analisis',
    getParentRoute: () => AuthenticatedAdminLaporanRoute,
  } as any)
const AuthenticatedAdminHasilIdRoute =
  AuthenticatedAdminHasilIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminHasilRoute,
  } as any)
const AuthenticatedAdminEvaluasiIdRoute =
  AuthenticatedAdminEvaluasiIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEvaluasiRoute,
  } as any)
const AuthenticatedPesertaUjianIdKerjakanRoute =
  AuthenticatedPesertaUjianIdKerjakanRouteImport.update({
    id: '/kerjakan',
    path: '/kerjakan',
    getParentRoute: () => AuthenticatedPesertaUjianIdRoute,
  } as any)
const AuthenticatedPesertaUjianIdHasilRoute =
  AuthenticatedPesertaUjianIdHasilRouteImport.update({
    id: '/hasil',
    path: '/hasil',
    getParentRoute: () => AuthenticatedPesertaUjianIdRoute,
  } as any)
const AuthenticatedAdminUjianIdTokenRoute =
  AuthenticatedAdminUjianIdTokenRouteImport.update({
    id: '/token',
    path: '/token',
    getParentRoute: () => AuthenticatedAdminUjianIdRoute,
  } as any)
const AuthenticatedAdminUjianIdPesertaRoute =
  AuthenticatedAdminUjianIdPesertaRouteImport.update({
    id: '/peserta',
    path: '/peserta',
    getParentRoute: () => AuthenticatedAdminUjianIdRoute,
  } as any)
const AuthenticatedAdminTopikIdSoalRoute =
  AuthenticatedAdminTopikIdSoalRouteImport.update({
    id: '/topik/$id/soal',
    path: '/topik/$id/soal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulIdTopikRoute =
  AuthenticatedAdminModulIdTopikRouteImport.update({
    id: '/$id/topik',
    path: '/$id/topik',
    getParentRoute: () => AuthenticatedAdminModulRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/peserta': typeof AuthenticatedPesertaRouteWithChildren
  '/admin/evaluasi': typeof AuthenticatedAdminEvaluasiRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/hasil': typeof AuthenticatedAdminHasilRouteWithChildren
  '/admin/laporan': typeof AuthenticatedAdminLaporanRouteWithChildren
  '/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/peserta': typeof AuthenticatedAdminPesertaRouteWithChildren
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/peserta/': typeof AuthenticatedPesertaIndexRoute
  '/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/admin/hasil/$id': typeof AuthenticatedAdminHasilIdRoute
  '/admin/laporan/analisis': typeof AuthenticatedAdminLaporanAnalisisRoute
  '/admin/laporan/rekap': typeof AuthenticatedAdminLaporanRekapRoute
  '/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/admin/peserta/group': typeof AuthenticatedAdminPesertaGroupRoute
  '/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/peserta/ujian/$id': typeof AuthenticatedPesertaUjianIdRouteWithChildren
  '/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/evaluasi': typeof AuthenticatedAdminEvaluasiRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/hasil': typeof AuthenticatedAdminHasilRouteWithChildren
  '/admin/laporan': typeof AuthenticatedAdminLaporanRouteWithChildren
  '/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/peserta': typeof AuthenticatedAdminPesertaRouteWithChildren
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/peserta': typeof AuthenticatedPesertaIndexRoute
  '/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/admin/hasil/$id': typeof AuthenticatedAdminHasilIdRoute
  '/admin/laporan/analisis': typeof AuthenticatedAdminLaporanAnalisisRoute
  '/admin/laporan/rekap': typeof AuthenticatedAdminLaporanRekapRoute
  '/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/admin/peserta/group': typeof AuthenticatedAdminPesertaGroupRoute
  '/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/peserta/ujian/$id': typeof AuthenticatedPesertaUjianIdRouteWithChildren
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/peserta': typeof AuthenticatedPesertaRouteWithChildren
  '/_authenticated/admin/evaluasi': typeof AuthenticatedAdminEvaluasiRouteWithChildren
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/hasil': typeof AuthenticatedAdminHasilRouteWithChildren
  '/_authenticated/admin/laporan': typeof AuthenticatedAdminLaporanRouteWithChildren
  '/_authenticated/admin/modul': typeof AuthenticatedAdminModulRouteWithChildren
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/peserta': typeof AuthenticatedAdminPesertaRouteWithChildren
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/ujian': typeof AuthenticatedAdminUjianRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/api/files/$id': typeof ApiFilesIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/peserta/': typeof AuthenticatedPesertaIndexRoute
  '/_authenticated/admin/evaluasi/$id': typeof AuthenticatedAdminEvaluasiIdRoute
  '/_authenticated/admin/hasil/$id': typeof AuthenticatedAdminHasilIdRoute
  '/_authenticated/admin/laporan/analisis': typeof AuthenticatedAdminLaporanAnalisisRoute
  '/_authenticated/admin/laporan/rekap': typeof AuthenticatedAdminLaporanRekapRoute
  '/_authenticated/admin/leaderboard/$id': typeof AuthenticatedAdminLeaderboardIdRoute
  '/_authenticated/admin/modul/import': typeof AuthenticatedAdminModulImportRoute
  '/_authenticated/admin/modul/import-word': typeof AuthenticatedAdminModulImportWordRoute
  '/_authenticated/admin/peserta/group': typeof AuthenticatedAdminPesertaGroupRoute
  '/_authenticated/admin/peserta/kartu': typeof AuthenticatedAdminPesertaKartuRoute
  '/_authenticated/admin/peserta/online': typeof AuthenticatedAdminPesertaOnlineRoute
  '/_authenticated/admin/ujian/$id': typeof AuthenticatedAdminUjianIdRouteWithChildren
  '/_authenticated/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/_authenticated/peserta/ujian/$id': typeof AuthenticatedPesertaUjianIdRouteWithChildren
  '/_authenticated/admin/leaderboard/': typeof AuthenticatedAdminLeaderboardIndexRoute
  '/_authenticated/admin/modul/$id/topik': typeof AuthenticatedAdminModulIdTopikRoute
  '/_authenticated/admin/topik/$id/soal': typeof AuthenticatedAdminTopikIdSoalRoute
  '/_authenticated/admin/ujian/$id/peserta': typeof AuthenticatedAdminUjianIdPesertaRoute
  '/_authenticated/admin/ujian/$id/token': typeof AuthenticatedAdminUjianIdTokenRoute
  '/_authenticated/peserta/ujian/$id/hasil': typeof AuthenticatedPesertaUjianIdHasilRoute
  '/_authenticated/peserta/ujian/$id/kerjakan': typeof AuthenticatedPesertaUjianIdKerjakanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/peserta'
    | '/admin/evaluasi'
    | '/admin/files'
    | '/admin/hasil'
    | '/admin/laporan'
    | '/admin/modul'
    | '/admin/pengaturan'
    | '/admin/peserta'
    | '/admin/tools'
    | '/admin/ujian'
    | '/admin/users'
    | '/api/files/$id'
    | '/admin/'
    | '/peserta/'
    | '/admin/evaluasi/$id'
    | '/admin/hasil/$id'
    | '/admin/laporan/analisis'
    | '/admin/laporan/rekap'
    | '/admin/leaderboard/$id'
    | '/admin/modul/import'
    | '/admin/modul/import-word'
    | '/admin/peserta/group'
    | '/admin/peserta/kartu'
    | '/admin/peserta/online'
    | '/admin/ujian/$id'
    | '/admin/users/roles'
    | '/peserta/ujian/$id'
    | '/admin/leaderboard/'
    | '/admin/modul/$id/topik'
    | '/admin/topik/$id/soal'
    | '/admin/ujian/$id/peserta'
    | '/admin/ujian/$id/token'
    | '/peserta/ujian/$id/hasil'
    | '/peserta/ujian/$id/kerjakan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/evaluasi'
    | '/admin/files'
    | '/admin/hasil'
    | '/admin/laporan'
    | '/admin/modul'
    | '/admin/pengaturan'
    | '/admin/peserta'
    | '/admin/tools'
    | '/admin/ujian'
    | '/admin/users'
    | '/api/files/$id'
    | '/admin'
    | '/peserta'
    | '/admin/evaluasi/$id'
    | '/admin/hasil/$id'
    | '/admin/laporan/analisis'
    | '/admin/laporan/rekap'
    | '/admin/leaderboard/$id'
    | '/admin/modul/import'
    | '/admin/modul/import-word'
    | '/admin/peserta/group'
    | '/admin/peserta/kartu'
    | '/admin/peserta/online'
    | '/admin/ujian/$id'
    | '/admin/users/roles'
    | '/peserta/ujian/$id'
    | '/admin/leaderboard'
    | '/admin/modul/$id/topik'
    | '/admin/topik/$id/soal'
    | '/admin/ujian/$id/peserta'
    | '/admin/ujian/$id/token'
    | '/peserta/ujian/$id/hasil'
    | '/peserta/ujian/$id/kerjakan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/peserta'
    | '/_authenticated/admin/evaluasi'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/hasil'
    | '/_authenticated/admin/laporan'
    | '/_authenticated/admin/modul'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/peserta'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/ujian'
    | '/_authenticated/admin/users'
    | '/api/files/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/peserta/'
    | '/_authenticated/admin/evaluasi/$id'
    | '/_authenticated/admin/hasil/$id'
    | '/_authenticated/admin/laporan/analisis'
    | '/_authenticated/admin/laporan/rekap'
    | '/_authenticated/admin/leaderboard/$id'
    | '/_authenticated/admin/modul/import'
    | '/_authenticated/admin/modul/import-word'
    | '/_authenticated/admin/peserta/group'
    | '/_authenticated/admin/peserta/kartu'
    | '/_authenticated/admin/peserta/online'
    | '/_authenticated/admin/ujian/$id'
    | '/_authenticated/admin/users/roles'
    | '/_authenticated/peserta/ujian/$id'
    | '/_authenticated/admin/leaderboard/'
    | '/_authenticated/admin/modul/$id/topik'
    | '/_authenticated/admin/topik/$id/soal'
    | '/_authenticated/admin/ujian/$id/peserta'
    | '/_authenticated/admin/ujian/$id/token'
    | '/_authenticated/peserta/ujian/$id/hasil'
    | '/_authenticated/peserta/ujian/$id/kerjakan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/peserta': {
      id: '/_authenticated/peserta'
      path: '/peserta'
      fullPath: '/peserta'
      preLoaderRoute: typeof AuthenticatedPesertaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peserta/': {
      id: '/_authenticated/peserta/'
      path: '/'
      fullPath: '/peserta/'
      preLoaderRoute: typeof AuthenticatedPesertaIndexRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ujian': {
      id: '/_authenticated/admin/ujian'
      path: '/ujian'
      fullPath: '/admin/ujian'
      preLoaderRoute: typeof AuthenticatedAdminUjianRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/peserta': {
      id: '/_authenticated/admin/peserta'
      path: '/peserta'
      fullPath: '/admin/peserta'
      preLoaderRoute: typeof AuthenticatedAdminPesertaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modul': {
      id: '/_authenticated/admin/modul'
      path: '/modul'
      fullPath: '/admin/modul'
      preLoaderRoute: typeof AuthenticatedAdminModulRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/laporan': {
      id: '/_authenticated/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AuthenticatedAdminLaporanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hasil': {
      id: '/_authenticated/admin/hasil'
      path: '/hasil'
      fullPath: '/admin/hasil'
      preLoaderRoute: typeof AuthenticatedAdminHasilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evaluasi': {
      id: '/_authenticated/admin/evaluasi'
      path: '/evaluasi'
      fullPath: '/admin/evaluasi'
      preLoaderRoute: typeof AuthenticatedAdminEvaluasiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leaderboard/': {
      id: '/_authenticated/admin/leaderboard/'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard/'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/peserta/ujian/$id': {
      id: '/_authenticated/peserta/ujian/$id'
      path: '/ujian/$id'
      fullPath: '/peserta/ujian/$id'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdRouteImport
      parentRoute: typeof AuthenticatedPesertaRoute
    }
    '/_authenticated/admin/users/roles': {
      id: '/_authenticated/admin/users/roles'
      path: '/roles'
      fullPath: '/admin/users/roles'
      preLoaderRoute: typeof AuthenticatedAdminUsersRolesRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/ujian/$id': {
      id: '/_authenticated/admin/ujian/$id'
      path: '/$id'
      fullPath: '/admin/ujian/$id'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdRouteImport
      parentRoute: typeof AuthenticatedAdminUjianRoute
    }
    '/_authenticated/admin/peserta/online': {
      id: '/_authenticated/admin/peserta/online'
      path: '/online'
      fullPath: '/admin/peserta/online'
      preLoaderRoute: typeof AuthenticatedAdminPesertaOnlineRouteImport
      parentRoute: typeof AuthenticatedAdminPesertaRoute
    }
    '/_authenticated/admin/peserta/kartu': {
      id: '/_authenticated/admin/peserta/kartu'
      path: '/kartu'
      fullPath: '/admin/peserta/kartu'
      preLoaderRoute: typeof AuthenticatedAdminPesertaKartuRouteImport
      parentRoute: typeof AuthenticatedAdminPesertaRoute
    }
    '/_authenticated/admin/peserta/group': {
      id: '/_authenticated/admin/peserta/group'
      path: '/group'
      fullPath: '/admin/peserta/group'
      preLoaderRoute: typeof AuthenticatedAdminPesertaGroupRouteImport
      parentRoute: typeof AuthenticatedAdminPesertaRoute
    }
    '/_authenticated/admin/modul/import-word': {
      id: '/_authenticated/admin/modul/import-word'
      path: '/import-word'
      fullPath: '/admin/modul/import-word'
      preLoaderRoute: typeof AuthenticatedAdminModulImportWordRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
    '/_authenticated/admin/modul/import': {
      id: '/_authenticated/admin/modul/import'
      path: '/import'
      fullPath: '/admin/modul/import'
      preLoaderRoute: typeof AuthenticatedAdminModulImportRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
    '/_authenticated/admin/leaderboard/$id': {
      id: '/_authenticated/admin/leaderboard/$id'
      path: '/leaderboard/$id'
      fullPath: '/admin/leaderboard/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/laporan/rekap': {
      id: '/_authenticated/admin/laporan/rekap'
      path: '/rekap'
      fullPath: '/admin/laporan/rekap'
      preLoaderRoute: typeof AuthenticatedAdminLaporanRekapRouteImport
      parentRoute: typeof AuthenticatedAdminLaporanRoute
    }
    '/_authenticated/admin/laporan/analisis': {
      id: '/_authenticated/admin/laporan/analisis'
      path: '/analisis'
      fullPath: '/admin/laporan/analisis'
      preLoaderRoute: typeof AuthenticatedAdminLaporanAnalisisRouteImport
      parentRoute: typeof AuthenticatedAdminLaporanRoute
    }
    '/_authenticated/admin/hasil/$id': {
      id: '/_authenticated/admin/hasil/$id'
      path: '/$id'
      fullPath: '/admin/hasil/$id'
      preLoaderRoute: typeof AuthenticatedAdminHasilIdRouteImport
      parentRoute: typeof AuthenticatedAdminHasilRoute
    }
    '/_authenticated/admin/evaluasi/$id': {
      id: '/_authenticated/admin/evaluasi/$id'
      path: '/$id'
      fullPath: '/admin/evaluasi/$id'
      preLoaderRoute: typeof AuthenticatedAdminEvaluasiIdRouteImport
      parentRoute: typeof AuthenticatedAdminEvaluasiRoute
    }
    '/_authenticated/peserta/ujian/$id/kerjakan': {
      id: '/_authenticated/peserta/ujian/$id/kerjakan'
      path: '/kerjakan'
      fullPath: '/peserta/ujian/$id/kerjakan'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdKerjakanRouteImport
      parentRoute: typeof AuthenticatedPesertaUjianIdRoute
    }
    '/_authenticated/peserta/ujian/$id/hasil': {
      id: '/_authenticated/peserta/ujian/$id/hasil'
      path: '/hasil'
      fullPath: '/peserta/ujian/$id/hasil'
      preLoaderRoute: typeof AuthenticatedPesertaUjianIdHasilRouteImport
      parentRoute: typeof AuthenticatedPesertaUjianIdRoute
    }
    '/_authenticated/admin/ujian/$id/token': {
      id: '/_authenticated/admin/ujian/$id/token'
      path: '/token'
      fullPath: '/admin/ujian/$id/token'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdTokenRouteImport
      parentRoute: typeof AuthenticatedAdminUjianIdRoute
    }
    '/_authenticated/admin/ujian/$id/peserta': {
      id: '/_authenticated/admin/ujian/$id/peserta'
      path: '/peserta'
      fullPath: '/admin/ujian/$id/peserta'
      preLoaderRoute: typeof AuthenticatedAdminUjianIdPesertaRouteImport
      parentRoute: typeof AuthenticatedAdminUjianIdRoute
    }
    '/_authenticated/admin/topik/$id/soal': {
      id: '/_authenticated/admin/topik/$id/soal'
      path: '/topik/$id/soal'
      fullPath: '/admin/topik/$id/soal'
      preLoaderRoute: typeof AuthenticatedAdminTopikIdSoalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modul/$id/topik': {
      id: '/_authenticated/admin/modul/$id/topik'
      path: '/$id/topik'
      fullPath: '/admin/modul/$id/topik'
      preLoaderRoute: typeof AuthenticatedAdminModulIdTopikRouteImport
      parentRoute: typeof AuthenticatedAdminModulRoute
    }
  }
}

interface AuthenticatedAdminEvaluasiRouteChildren {
  AuthenticatedAdminEvaluasiIdRoute: typeof AuthenticatedAdminEvaluasiIdRoute
}

const AuthenticatedAdminEvaluasiRouteChildren: AuthenticatedAdminEvaluasiRouteChildren =
  {
    AuthenticatedAdminEvaluasiIdRoute: AuthenticatedAdminEvaluasiIdRoute,
  }

const AuthenticatedAdminEvaluasiRouteWithChildren =
  AuthenticatedAdminEvaluasiRoute._addFileChildren(
    AuthenticatedAdminEvaluasiRouteChildren,
  )

interface AuthenticatedAdminHasilRouteChildren {
  AuthenticatedAdminHasilIdRoute: typeof AuthenticatedAdminHasilIdRoute
}

const AuthenticatedAdminHasilRouteChildren: AuthenticatedAdminHasilRouteChildren =
  {
    AuthenticatedAdminHasilIdRoute: AuthenticatedAdminHasilIdRoute,
  }

const AuthenticatedAdminHasilRouteWithChildren =
  AuthenticatedAdminHasilRoute._addFileChildren(
    AuthenticatedAdminHasilRouteChildren,
  )

interface AuthenticatedAdminLaporanRouteChildren {
  AuthenticatedAdminLaporanAnalisisRoute: typeof AuthenticatedAdminLaporanAnalisisRoute
  AuthenticatedAdminLaporanRekapRoute: typeof AuthenticatedAdminLaporanRekapRoute
}

const AuthenticatedAdminLaporanRouteChildren: AuthenticatedAdminLaporanRouteChildren =
  {
    AuthenticatedAdminLaporanAnalisisRoute:
      AuthenticatedAdminLaporanAnalisisRoute,
    AuthenticatedAdminLaporanRekapRoute: AuthenticatedAdminLaporanRekapRoute,
  }

const AuthenticatedAdminLaporanRouteWithChildren =
  AuthenticatedAdminLaporanRoute._addFileChildren(
    AuthenticatedAdminLaporanRouteChildren,
  )

interface AuthenticatedAdminModulRouteChildren {
  AuthenticatedAdminModulImportRoute: typeof AuthenticatedAdminModulImportRoute
  AuthenticatedAdminModulImportWordRoute: typeof AuthenticatedAdminModulImportWordRoute
  AuthenticatedAdminModulIdTopikRoute: typeof AuthenticatedAdminModulIdTopikRoute
}

const AuthenticatedAdminModulRouteChildren: AuthenticatedAdminModulRouteChildren =
  {
    AuthenticatedAdminModulImportRoute: AuthenticatedAdminModulImportRoute,
    AuthenticatedAdminModulImportWordRoute:
      AuthenticatedAdminModulImportWordRoute,
    AuthenticatedAdminModulIdTopikRoute: AuthenticatedAdminModulIdTopikRoute,
  }

const AuthenticatedAdminModulRouteWithChildren =
  AuthenticatedAdminModulRoute._addFileChildren(
    AuthenticatedAdminModulRouteChildren,
  )

interface AuthenticatedAdminPesertaRouteChildren {
  AuthenticatedAdminPesertaGroupRoute: typeof AuthenticatedAdminPesertaGroupRoute
  AuthenticatedAdminPesertaKartuRoute: typeof AuthenticatedAdminPesertaKartuRoute
  AuthenticatedAdminPesertaOnlineRoute: typeof AuthenticatedAdminPesertaOnlineRoute
}

const AuthenticatedAdminPesertaRouteChildren: AuthenticatedAdminPesertaRouteChildren =
  {
    AuthenticatedAdminPesertaGroupRoute: AuthenticatedAdminPesertaGroupRoute,
    AuthenticatedAdminPesertaKartuRoute: AuthenticatedAdminPesertaKartuRoute,
    AuthenticatedAdminPesertaOnlineRoute: AuthenticatedAdminPesertaOnlineRoute,
  }

const AuthenticatedAdminPesertaRouteWithChildren =
  AuthenticatedAdminPesertaRoute._addFileChildren(
    AuthenticatedAdminPesertaRouteChildren,
  )

interface AuthenticatedAdminUjianIdRouteChildren {
  AuthenticatedAdminUjianIdPesertaRoute: typeof AuthenticatedAdminUjianIdPesertaRoute
  AuthenticatedAdminUjianIdTokenRoute: typeof AuthenticatedAdminUjianIdTokenRoute
}

const AuthenticatedAdminUjianIdRouteChildren: AuthenticatedAdminUjianIdRouteChildren =
  {
    AuthenticatedAdminUjianIdPesertaRoute:
      AuthenticatedAdminUjianIdPesertaRoute,
    AuthenticatedAdminUjianIdTokenRoute: AuthenticatedAdminUjianIdTokenRoute,
  }

const AuthenticatedAdminUjianIdRouteWithChildren =
  AuthenticatedAdminUjianIdRoute._addFileChildren(
    AuthenticatedAdminUjianIdRouteChildren,
  )

interface AuthenticatedAdminUjianRouteChildren {
  AuthenticatedAdminUjianIdRoute: typeof AuthenticatedAdminUjianIdRouteWithChildren
}

const AuthenticatedAdminUjianRouteChildren: AuthenticatedAdminUjianRouteChildren =
  {
    AuthenticatedAdminUjianIdRoute: AuthenticatedAdminUjianIdRouteWithChildren,
  }

const AuthenticatedAdminUjianRouteWithChildren =
  AuthenticatedAdminUjianRoute._addFileChildren(
    AuthenticatedAdminUjianRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersRolesRoute: typeof AuthenticatedAdminUsersRolesRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersRolesRoute: AuthenticatedAdminUsersRolesRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEvaluasiRoute: typeof AuthenticatedAdminEvaluasiRouteWithChildren
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminHasilRoute: typeof AuthenticatedAdminHasilRouteWithChildren
  AuthenticatedAdminLaporanRoute: typeof AuthenticatedAdminLaporanRouteWithChildren
  AuthenticatedAdminModulRoute: typeof AuthenticatedAdminModulRouteWithChildren
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminPesertaRoute: typeof AuthenticatedAdminPesertaRouteWithChildren
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminUjianRoute: typeof AuthenticatedAdminUjianRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLeaderboardIdRoute: typeof AuthenticatedAdminLeaderboardIdRoute
  AuthenticatedAdminLeaderboardIndexRoute: typeof AuthenticatedAdminLeaderboardIndexRoute
  AuthenticatedAdminTopikIdSoalRoute: typeof AuthenticatedAdminTopikIdSoalRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEvaluasiRoute: AuthenticatedAdminEvaluasiRouteWithChildren,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminHasilRoute: AuthenticatedAdminHasilRouteWithChildren,
  AuthenticatedAdminLaporanRoute: AuthenticatedAdminLaporanRouteWithChildren,
  AuthenticatedAdminModulRoute: AuthenticatedAdminModulRouteWithChildren,
  AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
  AuthenticatedAdminPesertaRoute: AuthenticatedAdminPesertaRouteWithChildren,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminUjianRoute: AuthenticatedAdminUjianRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLeaderboardIdRoute: AuthenticatedAdminLeaderboardIdRoute,
  AuthenticatedAdminLeaderboardIndexRoute:
    AuthenticatedAdminLeaderboardIndexRoute,
  AuthenticatedAdminTopikIdSoalRoute: AuthenticatedAdminTopikIdSoalRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPesertaUjianIdRouteChildren {
  AuthenticatedPesertaUjianIdHasilRoute: typeof AuthenticatedPesertaUjianIdHasilRoute
  AuthenticatedPesertaUjianIdKerjakanRoute: typeof AuthenticatedPesertaUjianIdKerjakanRoute
}

const AuthenticatedPesertaUjianIdRouteChildren: AuthenticatedPesertaUjianIdRouteChildren =
  {
    AuthenticatedPesertaUjianIdHasilRoute:
      AuthenticatedPesertaUjianIdHasilRoute,
    AuthenticatedPesertaUjianIdKerjakanRoute:
      AuthenticatedPesertaUjianIdKerjakanRoute,
  }

const AuthenticatedPesertaUjianIdRouteWithChildren =
  AuthenticatedPesertaUjianIdRoute._addFileChildren(
    AuthenticatedPesertaUjianIdRouteChildren,
  )

interface AuthenticatedPesertaRouteChildren {
  AuthenticatedPesertaIndexRoute: typeof AuthenticatedPesertaIndexRoute
  AuthenticatedPesertaUjianIdRoute: typeof AuthenticatedPesertaUjianIdRouteWithChildren
}

const AuthenticatedPesertaRouteChildren: AuthenticatedPesertaRouteChildren = {
  AuthenticatedPesertaIndexRoute: AuthenticatedPesertaIndexRoute,
  AuthenticatedPesertaUjianIdRoute:
    AuthenticatedPesertaUjianIdRouteWithChildren,
}

const AuthenticatedPesertaRouteWithChildren =
  AuthenticatedPesertaRoute._addFileChildren(AuthenticatedPesertaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPesertaRoute: typeof AuthenticatedPesertaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPesertaRoute: AuthenticatedPesertaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
